version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SREEHARI
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
