version: "3"
# service is meant to describe the docker services cureently running
services:
  node-app:
  # means docker build
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8000:8000"
    volumes:
        - ./:/app
        - /app/node_modules
    env_file:
      - ./.env
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SREEHARI
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - monogo_db:/data/db
## refering the named mongodb volume globally
volumes:
  mongo_db: 